//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DMPreview.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_APC_TEST_DIALOG             102
#define IDS_APP_TITLE                   102
#define ID_INDICATOR_FPS                103
#define IDS_ERTON_DI_CLASS_NAME         107
#define IDR_MAINFRAME                   128
#define IDD_VIDEO_DEVICE_DLG            129
#define IDD_COLOR_DLG                   130
#define IDD_DEPTH_DLG                   131
#define IDD_DLG_WAIT                    132
#define IDD_DIALOG_PREVIEW_IMAGE        134
#define IDD_DIALOG_REGISTER_ACCESS      136
#define IDD_DIALOG_FLASH_ACCESS         138
#define IDD_DIALOG_RESIZING             139
#define IDD_DIALOG_AEAWBCTRL            140
#define IDD_MEASURE_DISTANCE_DLG        141
#define IDB_BITMAP_COLOR_BAR            145
#define IDD_DIALOG_IMU                  147
#define IDD_AUDIO_DLG                   151
#define IDC_DEVCOMBO                    1001
#define ID_OPEN_DEVICE                  1002
#define IDC_STATIC_SEL_STR              1003
#define IDC_STATIC_FW_VER               1004
#define IDC_STATIC_PID                  1005
#define IDC_STATIC_VID                  1006
#define IDC_EDIT_PID                    1007
#define IDC_EDIT_VID                    1008
#define IDC_ST_TEXT                     1009
#define IDC_STATIC_SN                   1011
#define IDC_EDIT_SN                     1012
#define IDC_STATIC_MODULE_INFO          1015
#define IDC_STATIC_REG_RW               1016
#define IDC_RADIO_I2C                   1017
#define IDC_RADIO_ASIC                  1018
#define IDC_RADIO_FW                    1019
#define IDC_STATIC_SLAVE_ID             1020
#define IDC_EDIT_SLAVE_ID               1021
#define IDC_STATIC_SLAVE_ID2            1022
#define IDC_STATIC_ADDR_SIZE            1023
#define IDC_STATIC_VAL_SIZE             1024
#define IDC_CHECK_ADDR_SIZE             1025
#define IDC_CHECK_VAL_SIZE              1026
#define IDC_STATIC_ADDR_CONTENT         1027
#define IDC_STATIC_VAL_CONTENT          1028
#define IDC_STATIC_ADDR_CONTENT3        1029
#define IDC_STATIC_VAL_CONTENT3         1030
#define IDC_STATIC_ADDR_CONTENT2        1031
#define IDC_STATIC_VAL_CONTENT2         1032
#define IDC_REG_READ_BTN                1033
#define IDC_REG_WRITE_BTN               1034
#define IDC_STATIC_SENSOR_MODE          1035
#define IDC_STATIC_FLASH_RW             1038
#define IDC_CHECK_COLOR_STREAM          1039
#define IDC_STATIC_FLASH_RW2            1039
#define IDC_STATIC_AE_AWB               1040
#define IDC_CHECK_DEPTH1                1041
#define IDC_STATIC_PREVIEW_IMG          1042
#define IDC_COMBO_COLOR_STREAM          1043
#define IDC_COMBO_DEPTH_STREAM          1044
#define IDC_STATIC_DEPTH_OUTPUT_CTRL    1045
#define IDC_COMBO_DEPTH_OUTPUT_CTRL     1046
#define IDC_STATIC_COLOR_OUTPUT_CTRL    1047
#define IDC_COMBO_COLOR_OUTPUT_CTRL     1048
#define IDC_STATIC_SLAVE_ID3            1049
#define IDC_CHECK_PP                    1050
#define IDC_STATIC_SLAVE_ID4            1051
#define IDC_STATIC_PREVIEW_IMG2         1051
#define IDC_STATIC_FRAME_RATE           1052
#define IDC_PREVIEW_BTN                 1054
#define IDC_CHECK_DEPTH3                1055
#define IDC_CHECK_POINTCLOUD_VIEWER     1055
#define IDC_PREVIEW_BTN2                1055
#define IDC_EDIT_Self_K_Advance_Operator_do_calibration_btn 1055
#define IDC_PREVIEW_BTN3                1056
#define IDC_EDIT_Self_K_Advance_Operator_apply_before_reg_btn 1056
#define IDC_PREVIEW_BTN4                1057
#define IDC_EDIT_Self_K_Advance_Operator_apply_after_reg_btn 1057
#define IDC_PREVIEW_BTN5                1058
#define IDC_EDIT_Self_K_Advance_Operator_apply_after_flash_btn 1058
#define IDC_PREVIEW_BTN6                1059
#define IDC_EDIT_Self_K_Advance_Operator_reset_all_btn 1059
#define IDC_OFFSET_READ                 1065
#define IDC_OFFSET_WRITE                1066
#define IDC_RECTIFY_READ                1067
#define IDC_RECTIFY_WRITE               1068
#define IDC_ZD_READ                     1069
#define IDC_ZD_WRITE                    1070
#define IDC_LOGDATA_READ                1071
#define IDC_LOGDATA_WRITE               1072
#define IDC_USERDATA_READ               1073
#define IDC_USERDATA_WRITE              1074
#define IDC_FLASHTYPESELECTCOMBO        1075
#define IDC_FLASHDATA_READ              1076
#define IDC_FLASHDATA_WRITE             1077
#define IDC_COMBO_DEPTH_BIT_SEL_CTRL    1078
#define IDC_RECTIFYLOG_GET              1079
#define IDC_COMBO_DEPTH_INDEX           1080
#define IDC_FLASHTYPESELECTCOMBO2       1081
#define IDC_ZDDATATYPESELECTCOMBO2      1082
#define IDC_STATIC_DEPTH                1083
#define IDC_STATIC_DEPTH_BIT_SEL        1084
#define IDC_ZD_DATA_TYPE                1085
#define IDC_CHECK_360MODE               1086
#define IDC_CHECK_DEPTH0                1087
#define IDC_COMBO_SENSOR_TYPE           1088
#define IDC_CHECK_DEPTH_STREAM1         1089
#define IDC_CHECK_DEPTH2                1090
#define IDC_COMBO_SENSOR_MODE           1091
#define IDC_BUTTON_AE_ENABLE            1092
#define IDC_BUTTON_AWB_ENABLE           1093
#define IDC_EDIT_EXPTIME                1094
#define IDC_EDIT_GLOBAL_GAIN            1095
#define IDC_EDIT_COLOR_GAIN_R           1096
#define IDC_CHECK_PERIODIC_READ         1097
#define IDC_BUTTON_EXPTIME_READ         1098
#define IDC_EDIT_ACCESS_FREQUENCY       1100
#define IDC_BUTTON_GLOGAL_GAIN_READ     1101
#define IDC_BUTTON_COLOR_GAIN_READ      1102
#define IDC_EDIT_COLOR_GAIN_G           1103
#define IDC_EDIT_COLOR_GAIN_B           1104
#define IDC_BUTTON_EXPTIME_READ2        1105
#define IDC_BUTTON_EXPTIME_WRITE        1106
#define IDC_BUTTON_GLOGAL_GAIN_WRITE    1107
#define IDC_BUTTON_COLOR_GAIN_WRITE     1108
#define IDC_EDIT_ADDR_CONTENT0          1109
#define IDC_EDIT_ADDR_CONTENT1          1110
#define IDC_EDIT_ADDR_CONTENT2          1111
#define IDC_EDIT_ADDR_CONTENT3          1112
#define IDC_EDIT_ADDR_CONTENT4          1113
#define IDC_EDIT_ADDR_CONTENT5          1114
#define IDC_EDIT_VAL_CONTENT0           1115
#define IDC_EDIT_VAL_CONTENT1           1116
#define IDC_EDIT_VAL_CONTENT2           1117
#define IDC_EDIT_VAL_CONTENT3           1118
#define IDC_EDIT_VAL_CONTENT4           1119
#define IDC_EDIT_VAL_CONTENT5           1120
#define IDC_RADIO_SENSOR1               1121
#define IDC_RADIO_SENSOR2               1122
#define IDC_RADIO_SENSOR3               1123
#define IDC_RADIO_SENSOR4               1124
#define IDC_RADIO_SENSOR_ALL            1125
#define IDC_STATIC_IR                   1126
#define IDC_EDIT_ADDR_CONTENT6          1126
#define IDC_SLIDER_IR                   1127
#define IDC_EDIT_VAL_CONTENT6           1127
#define IDC_STATIC_IR_VALUE             1128
#define IDC_EDIT_ADDR_CONTENT7          1128
#define IDC_CHECK_SAVELOG_PERIODIC_READ 1129
#define IDC_RADIO_RAW_DATA              1130
#define IDC_EDIT_VAL_CONTENT7           1130
#define IDC_RADIO_RECTIFY_DATA          1131
#define IDC_STATIC_ACTUAL_PERIOD        1132
#define IDC_CHECK_DEPTH_FUSION          1133
#define IDC_RADIO_AE_ON                 1134
#define IDC_RADIO_AE_OFF                1135
#define IDC_RADIO_AWB_ON                1136
#define IDC_RADIO_AWB_OFF               1137
#define IDC_STATIC_DEPTH_MAPPING        1138
#define IDC_RADIO_DEPTH_MAPPING_ZDTABLE 1139
#define IDC_RADIO_DEPTH_MAPPING_MANUAL  1140
#define IDC_STATIC_CAM_FOCUS            1141
#define IDC_STATIC_BASELINE_DIST        1142
#define IDC_EDIT_CAM_FOCUS              1143
#define IDC_EDIT_BLDIST0                1144
#define IDC_EDIT_BLDIST1                1145
#define IDC_EDIT_BLDIST2                1146
#define IDC_STATIC_BSDIST_UNIT          1147
#define IDC_CHECK_ENABLE_SDK_LOG        1148
#define IDC_CHECK_HARDWARE_POSTPROC     1149
#define IDC_CHECK_FUSION_SELECT_DLG     1154
#define IDC_CHECK_FUSION_SWPP           1155
#define IDC_STATIC_FW_VER_TITLE         1156
#define IDC_CHECK_INTERLEAVE_MODE       1157
#define IDC_STATIC_USERDATA_INDEX       1158
#define IDC_COMBO_USERDATA_INDEX        1159
#define IDC_STATIC_USERDATA_BUFSIZE     1160
#define IDC_EDIT_USERDATA_BUFSIZE       1161
#define IDC_EDIT1                       1162
#define IDC_EDIT_ZFAR                   1162
#define IDC_AUDIO_RANGE                 1162
#define IDC_ED_TF_HISTORY               1162
#define IDC_ED_TEMPORAL_NOISE           1162
#define IDC_EDIT_RTC_HOUR               1162
#define IDC_EDIT_MODE                   1162
#define IDC_EDIT_ZFAR2                  1163
#define IDC_SELF_K_Basic_Times          1163
#define IDC_EDIT_RTC_MINUTE             1163
#define IDC_STATIC_Z_FAR_TEXT           1164
#define IDC_EDIT_RTC_SECOND             1164
#define IDC_STATIC_Z_FAR_TEXT2          1165
#define IDC_SNAPSHOT_BTN                1166
#define IDC_EDIT_OUT_AND_INFO           1166
#define IDC_SNAPSHOT_BTN2               1167
#define IDC_EDIT_Self_K_Advance_Write_Strategy_btn 1167
#define IDC_EDIT_Self_K_Advance_Strategy_write_btn 1167
#define IDC_SNAPSHOT_BTN3               1168
#define IDC_EDIT_Self_K_Advance_Reset_Strategy_btn 1168
#define IDC_EDIT_Self_K_Advance_Strategy_reset_btn 1168
#define IDC_EDIT_ZNEAR                  1169
#define IDC_SNAPSHOT_BTN4               1169
#define IDC_IDC_SELF_K_Basic_Resetall_Btn 1169
#define IDC_STATIC_PIC_COLOR_BAR        1172
#define IDC_SLAVECHK                    1173
#define IDC_CHECK_ROTATE_IMG            1175
#define IDC_LEFT_CROSS                  1177
#define IDC_MIDDLE_CROSS                1178
#define IDC_RIGHT_CROSS                 1179
#define IDC_STATIC_Z_FAR_TEXT5          1181
#define IDC_STATIC_FILTER_FACTOR_PER    1181
#define IDC_FRAME_SYNC                  1183
#define IDC_STATIC_PLUGIN_DATA          1194
#define IDC_STATIC_RECTIFYLOG           1195
#define IDC_STATIC_IMU_OUPUT            1198
#define IDC_STATIC_IMU_OUPUT2           1199
#define IDC_AUDIO_BTN                   1201
#define IDC_CHECK_T_COLOR_STREAM        1201
#define IDC_STATIC_AUDIO                1202
#define IDC_COMBO_T_COLOR_STREAM        1202
#define IDC_AudioStatus                 1203
#define IDC_CHECK_K_COLOR_STREAM        1204
#define IDC_COMBO_K_COLOR_STREAM        1205
#define IDC_BUTTON_SAVE_IMU_RAW_DATA    1206
#define IDC_BUTTON_GET_FW_VERSION       1207
#define IDC_BUTTON_GET_MODULE_NAME      1208
#define IDC_BUTTON_GET_INPUT_REPORT     1209
#define IDC_BUTTON_SET_OUTPUT_REPORT    1210
#define IDC_BUTTON_ENABLE_IMU           1211
#define IDC_BUTTON_DISABLE_IMU          1212
#define IDC_BUTTON_GET_IMU_STATUS       1213
#define IDC_BUTTON_START_CALIBRATION    1214
#define IDC_COMBO_SET_IMU_DATA_FORMAT   1215
#define IDC_BUTTON_RTC_READ             1216
#define IDC_BUTTON_RTC_WRITE            1217
#define IDC_BUTTON_ACC_FS_READ          1218
#define IDC_BUTTON_ACC_FS_WRITE         1219
#define IDC_BUTTON_GYR_FS_READ          1220
#define IDC_BUTTON_GYR_FS_WRITE         1221
#define IDD_AEAWB_PROPERTY_DIALOG       1302
#define IDC_COMBO_DEVICE_TYPE_CTRL      1304
#define IDC_CHECK_AE                    1305
#define IDD_DLG_DISTANCE_ACCURACY       1305
#define IDC_CHECK_AWB                   1306
#define IDD_DLG_DEPTHFILTER             1307
#define IDC_STATIC_LIGHT_SOURCE         1308
#define IDD_AUTO_MODULE_SYNC            1308
#define IDD_AUTO_MODULE_SYNC_DIALOG     1308
#define IDC_STATIC_LOW_LIGHT_COMPENSATION 1309
#define IDD_SELF_K2_DIALOG              1309
#define IDD_Self_CalibrationDlg         1309
#define IDD_SELF_CALIBRATION_DIALOG     1309
#define IDD_SPARSE_MODE                 1310
#define IDC_STATIC_EXPOSURE             1310
#define IDC_STATIC_WB_TEMPERATURE       1311
#define IDC_SLIDER_EXPOSURE_TIME        1312
#define IDC_STATIC_TEXT_PGAIN           1312
#define IDC_STATIC_EXPOSURE_TIME_RANGE  1313
#define IDC_STATIC_TEXT_NGAIN           1313
#define IDC_SLIDER_WB_TEMPERATURE       1314
#define IDC_STATIC_AB_TEMPERATURE_RANGE 1315
#define IDC_RADIO_50HZ                  1316
#define IDC_SLIDER_EXPOSURE_TIME2       1316
#define IDC_SLIDER_SGBM_SAD_THD         1316
#define IDC_SLIDER_SGBM_SAD_RATIO       1316
#define IDC_RADIO_60HZ                  1317
#define IDC_STATIC_EXPOSURE_TIME_RANGE2 1317
#define IDC_STATIC_DEPTH_LRCHECK_DIFF_RANGE 1317
#define IDC_RADIO_LLC_ON                1318
#define IDC_STATIC_SPARSE_THD           1318
#define IDC_RADIO_LLC_OFF               1319
#define IDC_SLIDER_WB_TEMPERATURE2      1319
#define IDC_SLIDER_TEXT_NGAIN           1319
#define IDC_STATIC_EXPOSURE2            1320
#define IDC_STATIC_DEPTH_LRCHECK_DIFF   1320
#define IDC_SLIDER_TEXT_PGAIN           1321
#define IDC_SLIDER_SPARSE_THD           1322
#define IDC_SLIDER_SGBM_SAD_THD2        1323
#define IDC_SLIDER_SGBM_SAD_RATIO2      1323
#define IDC_BUTTON_AEAWB_PROPERTY       1324
#define IDC_STATIC_TEXT_PGAIN_RANGE     1324
#define IDC_SLD_DEPTH_ROI               1325
#define IDC_STATIC_TEXT_NGAIN_RANGE     1325
#define IDC_ST_DEPTH_ROI                1326
#define IDC_STATIC_SPARSE_THD_RANGE     1326
#define IDC_ST_MODE_CONFIG              1328
#define IDC_COMBO_MODE_CONFIG           1329
#define IDC_COMBO_FRAME_RATE            1330
#define IDC_DEPTH_FRAME_RATE            1331
#define IDC_ST_DEPTH_FPS                1332
#define IDC_BT_Z_SET                    1333
#define IDC_BT_Z_RESET                  1334
#define IDC_CHK_MULTI_SYNC              1335
#define IDC_CHK_PLY_FILTER              1336
#define IDC_CHK_MASTER                  1337
#define IDC_ST_USBMODE                  1338
#define IDC_BT_PROPERTY_RESET           1339
#define IDC_TAB_PAGE                    1340
#define IDC_ST_AE_MIN                   1341
#define IDC_ST_AWB_MIN                  1342
#define IDC_ST_AE_MAX                   1343
#define IDC_ST_TEXT_PGAIN_MIN           1343
#define IDC_ST_AWB_MAX                  1344
#define IDC_CHK_IRMAX_EXT               1345
#define IDC_ST_AE_MIN2                  1345
#define IDC_ST_DEPTH_LRCHECK_DIFF_MIN   1345
#define IDC_SLD_PCL_PSIZE               1346
#define IDC_ST_AWB_MAX2                 1346
#define IDC_ST_DEPTH_LRCHECK_DIFF_MAX   1346
#define IDC_ST_PSIZE                    1347
#define IDC_ST_TEXT_NGAIN_MIN           1347
#define IDC_CHK_PCV_NOCOLOR             1348
#define IDC_ST_SPARSE_THD_MIN           1348
#define IDC_CHK_PCV_SINGLE              1349
#define IDC_ST_TEXT_PGAIN_MAX           1349
#define IDC_CHK_MANUALEXP               1350
#define IDC_ST_TEXT_NGAIN_MAX           1350
#define IDC_CB_INTEREST                 1351
#define IDC_ST_SPARSE_THD_MAX           1351
#define IDC_CHK_GROUNDTRUTH             1352
#define IDC_ED_PIXEL_UNIT               1353
#define IDC_ED_DISTANCE                 1354
#define IDC_ED_FILLRATE                 1355
#define IDC_ED_ZACCURACY                1356
#define IDC_CB_SUBSAMPLE_MODE           1357
#define IDC_ED_PIXEL_UNIT2              1357
#define IDC_ED_GROUNDTRUTH              1357
#define IDC_ED_LEFT_FX                  1358
#define IDC_CB_SUBSAMPLE_FACTOR         1359
#define IDC_ED_LEFT_FY                  1359
#define IDC_CHK_SUBSAMPLE_ENABLE        1360
#define IDC_CHK_HF_ENABLE               1361
#define IDC_ED_RIGHT_FX                 1361
#define IDC_ED_RIGHT_FY                 1362
#define IDC_CHK_HF_HRZ_ENABLE           1363
#define IDC_CHK_TF_ENABLE               1364
#define IDC_CHK_EPS_ENABLE              1365
#define IDC_SLD_HF_LEVEL                1366
#define IDC_SLD_TF_ALPHA                1367
#define IDC_SLD_EPS_LEVEL               1368
#define IDC_ST_EPS_LEVEL                1369
#define IDC_ST_HF_LEVEL                 1370
#define IDC_ST_TF_ALPHA                 1371
#define IDC_CHK_FILTER_ENABLE           1372
#define IDC_ED_EPS_LUMDA                1373
#define IDC_ED_EPS_SIGMA                1374
#define IDC_CHK_REMOVECURVE             1375
#define IDC_ED_SPATIAL_NOISE            1376
#define IDC_ED_ANGLE                    1377
#define IDC_CHK_MIN                     1378
#define IDC_CHK_FULL                    1379
#define IDC_ED_ANGLE_X                  1380
#define IDC_BUTTON1                     1381
#define IDC_IMU_3D_RESET                1381
#define IDC_BUTTON_ADJUST_FOCAL_LENGTH  1381
#define IDC_BTN_RUN                     1381
#define IDC_EDIT3                       1382
#define IDC_ED_ANGLE_Y                  1382
#define IDC_COMBO1                      1383
#define IDC_CB_DEPTHLIST                1383
#define IDC_COMBO_ACC_FS                1383
#define IDC_COMBO_DEVICE_LIST           1383
#define IDC_IMU_3D                      1384
#define IDC_IMU_VIEWER                  1385
#define IDC_COMBO_GYR_FS                1385
#define IDC_FOCAL_LENGTH                1386
#define IDC_SLIDER1                     1387
#define IDC_SLIDER_PIXEL_UNIT           1387
#define IDC_EDIT_DF_VERSION             1389
#define IDC_EDIT_STATIC_PID             1390
#define IDC_EDIT_STATIC_SN              1391
#define IDC_EDIT_STATIC_FW_VER_TITLE    1392
#define IDC_EDIT6                       1393
#define IDC_EDIT7                       1394
#define IDC_EDIT8                       1395
#define IDC_EDIT_STATIC_VID             1396
#define ID_SELECT_MASTER                1396
#define IDC_CHECK_FRAME_SYNC            1398
#define IDC_STATIC_TEMPERATURE          1399
#define IDC_TEMPERATURE_GET             1400
#define IDC_EDIT_TEMPERATURE            1401
#define IDC_EDIT_FORCE_OVERRIDE         1402
#define IDC_GRAB_FRAMES_BTN             1403
#define IDC_SLIDER_DEPTH_LRCHECK_DIFF   1422
#define IDC_STATIC_SGBM_SAD_THD         1423
#define IDC_ST_SGBM_SAD_THD_MIN         1424
#define IDC_STATIC_SGBM_SAD_THD_RANGE   1425
#define IDC_ST_SGBM_SAD_THD_MAX         1426
#define IDC_STATIC_TEXT_LMT             1427
#define IDC_ST_TEXT_LMT_MIN             1428
#define IDC_ST_TEXT_LMT_MAX             1429
#define IDC_STATIC_TEXT_LMT_RANGE       1430
#define IDC_SLIDER_TEXT_LMT             1431
#define IDC_STATIC_SGBM_SAD_RATIO       1432
#define IDC_ST_SGBM_SGBM_SAD_RATIO_MIN  1433
#define IDC_STATIC_SGBM_SAD_RATIO_RANGE 1434
#define IDC_ST_SGBM_SAD_THD_MAX2        1435
#define IDC_ST_SGBM_SAD_RATIO_MAX       1436
#define IDC_SPARSE_MODE_RESET           1437
#define IDC_CHK_ENABLE_SPARSE_MODE      1438
#define IDC_SPARSE_MODE_SAVE_CONFIG     1439
#define IDC_TEXT_ANALOG_GAIN            1440
#define IDC_TEXT_DIGITAL_GAIN           1441
#define IDC_EDIT_ANALOG_GAIN            1442
#define IDC_EDIT_DIGITAL_GAIN           1443
#define IDC_SPIN_ANALOG_GAIN            1444
#define IDC_SPIN_DIGITAL_GAIN           1445
#define IDC_BUTTON_ANALOG_GAIN_READ     1446
#define IDC_BUTTON_DIGITAL_GAIN_READ    1447
#define IDC_BUTTON_ANALOG_GAIN_WRITE    1448
#define IDC_BUTTON_DIGITAL_GAIN_WRITE   1449
#define IDC_GAIN_CONTROL                1450
#define IDC_LIST_GAIN_REGISTER          1451
#define IDC_STATIC_FLOODLED             1452
#define IDC_SLIDER_FLOODLED             1453
#define IDC_STATIC_FLOODLED_VALUE       1454
#define IDC_STATIC_TOGGLE_MODE          1455
#define IDC_COMBO_TOGGLE_MODE           1456
#define IDC_STATIC_RTC                  1457
#define IDC_STATIC_ACC_FS               1458
#define IDC_STATIC_GYR_FS               1459
#define IDC_RADIO_RUNTIME               1461
#define IDC_RADIO_REPAIR                1462
#define IDC_BTN_RESET                   1463
#define IDC_BTN_WRITE                   1464

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1309
#define _APS_NEXT_COMMAND_VALUE         1301
#define _APS_NEXT_CONTROL_VALUE         1466
#define _APS_NEXT_SYMED_VALUE           1304
#endif
#endif
