#pragma once

#define WM_MSG_CLOSE_PREVIEW_DLG (WM_APP + 1)
#define WM_MSG_UPDATE_MOUSE_POS_FROM_DIALOG (WM_APP + 2)
#define WM_MSG_CLOSE_VIDEO_DEVICE_DLG (WM_APP + 3)
//#define WM_MSG_RESET_PARAM (WM_APP + 4)
#define WM_MSG_UPDATE_DLG_TITLE (WM_APP + 5)
#define WM_MSG_SNAPSHOT (WM_APP + 6)
#define WM_MSG_SNAPSHOT_ALL (WM_APP + 8)
#define WM_MSG_SNAPSHOT_COMPLETE (WM_APP + 9)
#define WM_MSG_AUTO_PREVIEW  (WM_APP + 10)
